# Generated by Django 3.0.8 on 2020-07-15 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20200715_0430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='date',
        ),
        migrations.RemoveField(
            model_name='show',
            name='time',
        ),
        migrations.AddField(
            model_name='show',
            name='show_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 15, 6, 11, 18, 602399)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_type',
            field=models.CharField(choices=[('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], max_length=8),
        ),
    ]
