# Generated by Django 3.0.8 on 2020-07-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20200715_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='showsheatmapping',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Blocked', 'Blocked'), ('Empty', 'Empty')], default='Empty', max_length=11),
        ),
    ]
