# Generated by Django 3.0.8 on 2020-07-15 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_showsheatmapping_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='showsheatmapping',
            name='show',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.Show'),
            preserve_default=False,
        ),
    ]
